/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bittu_AudioPlayer */

#ifndef _Included_bittu_AudioPlayer
#define _Included_bittu_AudioPlayer
#ifdef __cplusplus
extern "C" {
#endif
#undef bittu_AudioPlayer_PLAYER_AUDIO_BUFFER_MAX_SIZE
#define bittu_AudioPlayer_PLAYER_AUDIO_BUFFER_MAX_SIZE 3840L
#undef bittu_AudioPlayer_PLAYER_NO_ERROR
#define bittu_AudioPlayer_PLAYER_NO_ERROR 0L
#undef bittu_AudioPlayer_PLAYER_MEDIA_INAUDIBLE
#define bittu_AudioPlayer_PLAYER_MEDIA_INAUDIBLE -1L
#undef bittu_AudioPlayer_PLAYER_MEDIA_INVALID
#define bittu_AudioPlayer_PLAYER_MEDIA_INVALID -2L
#undef bittu_AudioPlayer_PLAYER_MEDIA_DECODE_ERROR
#define bittu_AudioPlayer_PLAYER_MEDIA_DECODE_ERROR -3L
#undef bittu_AudioPlayer_PLAYER_MEDIA_INTERNAL_ERROR
#define bittu_AudioPlayer_PLAYER_MEDIA_INTERNAL_ERROR -4L
#undef bittu_AudioPlayer_PLAYER_MEDIA_EOF
#define bittu_AudioPlayer_PLAYER_MEDIA_EOF -5L
/*
 * Class:     bittu_AudioPlayer
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_bittu_AudioPlayer_init
  (JNIEnv *, jobject);

/*
 * Class:     bittu_AudioPlayer
 * Method:    stream
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_bittu_AudioPlayer_stream
  (JNIEnv *, jobject, jstring);

/*
 * Class:     bittu_AudioPlayer
 * Method:    get20ms
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_bittu_AudioPlayer_get20ms
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     bittu_AudioPlayer
 * Method:    uninit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_bittu_AudioPlayer_uninit
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
