/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bittu_jni_AudioPlayerJNI */

#ifndef _Included_bittu_jni_AudioPlayerJNI
#define _Included_bittu_jni_AudioPlayerJNI
#ifdef __cplusplus
extern "C" {
#endif
#undef bittu_jni_AudioPlayerJNI_AUDIO_BUFFER_MAX_SIZE
#define bittu_jni_AudioPlayerJNI_AUDIO_BUFFER_MAX_SIZE 3840L
#undef bittu_jni_AudioPlayerJNI_NO_ERROR
#define bittu_jni_AudioPlayerJNI_NO_ERROR 0L
#undef bittu_jni_AudioPlayerJNI_MEDIA_INAUDIBLE
#define bittu_jni_AudioPlayerJNI_MEDIA_INAUDIBLE -1L
#undef bittu_jni_AudioPlayerJNI_MEDIA_INVALID
#define bittu_jni_AudioPlayerJNI_MEDIA_INVALID -2L
#undef bittu_jni_AudioPlayerJNI_MEDIA_DECODE_ERROR
#define bittu_jni_AudioPlayerJNI_MEDIA_DECODE_ERROR -3L
#undef bittu_jni_AudioPlayerJNI_MEDIA_INTERNAL_ERROR
#define bittu_jni_AudioPlayerJNI_MEDIA_INTERNAL_ERROR -4L
#undef bittu_jni_AudioPlayerJNI_MEDIA_EOF
#define bittu_jni_AudioPlayerJNI_MEDIA_EOF -5L
/*
 * Class:     bittu_jni_AudioPlayerJNI
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_bittu_jni_AudioPlayerJNI_init
  (JNIEnv *, jobject);

/*
 * Class:     bittu_jni_AudioPlayerJNI
 * Method:    stream
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_bittu_jni_AudioPlayerJNI_stream
  (JNIEnv *, jobject, jstring);

/*
 * Class:     bittu_jni_AudioPlayerJNI
 * Method:    get20ms
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_bittu_jni_AudioPlayerJNI_get20ms
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     bittu_jni_AudioPlayerJNI
 * Method:    uninit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_bittu_jni_AudioPlayerJNI_uninit
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
