/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bittu_AudioPlayer */

#ifndef _Included_bittu_AudioPlayer
#define _Included_bittu_AudioPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bittu_AudioPlayer
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_bittu_AudioPlayer_init
  (JNIEnv *, jobject);

/*
 * Class:     bittu_AudioPlayer
 * Method:    stream
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_bittu_AudioPlayer_stream
  (JNIEnv *, jobject, jstring);

/*
 * Class:     bittu_AudioPlayer
 * Method:    get_20ms
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_bittu_AudioPlayer_get20ms
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     bittu_AudioPlayer
 * Method:    uninit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_bittu_AudioPlayer_uninit
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
